version: '3'
services:
  web:
    image: nginx:1.17
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/php:/usr/local/etc/php/custom.d
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"

  db:
    image: postgres:latest
    restart: always
    ports:
      - "3336:3306"
    volumes:
      - "./database/postgres-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  # uncomment, build to generate docs
  phpdoc:
    image: phpdoc/phpdoc:latest
    volumes:
      - ./:/var/www/html
    entrypoint: >
      /bin/sh -c "
        cd /var/www/html;
        phpdoc;

        exit 0;
      "

  # alternative to adminer
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #     - db
  #   restart: always
  #   ports:
  #     - 8080:80

  # alternative to phpmyadmin
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080